tests: Make simulate_network_failure_loop() stop on time

diff --git a/lib/functions b/lib/functions
--- a/lib/functions
+++ b/lib/functions
@@ -266,22 +266,52 @@ held_by() {
     done
 }
 
-simulate_network_failure_loop() {
-    local d s
+# System uptime in seconds.
+uptime_s() {
+    local a b
 
+    echo "$(</proc/uptime)" | { read -r a b && echo "${a%%.*}"; }
+}
+
+# Sleep until either $1 seconds have elapsed or until the deadline $2 has been
+# reached. Return 1 if and only if the deadline has been met.
+sleep_until() {
+    local duration=$1 deadline=$2 u
+
+    u=$(uptime_s)
+    if [ $((u + duration)) -le "$deadline" ]; then
+	sleep "$duration"
+    else
+	[ "$deadline" -gt "$u" ] && sleep $((deadline - u))
+	return 1
+    fi
+}
+
+# Simulate network failures for device $1 during $2 seconds.
+simulate_network_failure_loop() {
+    local d dev="$1" duration="$2" deadline i rc=0 s
+
+    [ -n "$duration" ] || return $?
+    deadline=$(($(uptime_s) + duration))
     s=5
-    while :; do
-	sleep 5
+    while [ $rc = 0 ]; do
+	sleep_until 5 ${deadline}
 	if [ -n "$nvme" ]; then
 	    for d in $(held_by "$dev"); do
 		echo 1 >"$d/device/reset_controller"
 	    done
 	else
 	    log_out
-	    sleep $s
+	    sleep_until $s ${deadline}
+	    rc=$?
 	    s=$((((s + 5) & 0xff) ^ 0xa6))
 	    log_in ""
 	fi
+    done
+
+    for ((i=0;i<5;i++)); do
+	log_in "" && break
+	sleep 1
     done
 }
 
