lib/functions, remove_mpath_dev(): Do not fail if a device has already been removed

diff --git a/lib/functions b/lib/functions
--- a/lib/functions
+++ b/lib/functions
@@ -364,25 +364,38 @@ dev_to_mpath() {
 remove_mpath_dev() {
     local cmd dm i output t1 t2
 
-    cmd="dm=\$(dev_to_mpath \"$1\")"
-    eval "$cmd" || { echo "$cmd: failed"; return 1; }
-    t1=$(dmsetup table "$dm")
-    cmd="dmsetup message $dm 0 fail_if_no_path"
-    eval "$cmd" || { echo "$cmd: failed"; return 1; }
-    t2=$(dmsetup table "$dm")
-    if echo "$t2" | grep -qw queue_if_no_path; then
-	echo "$dm: $t1 -> $t2"
-    fi
     for ((i=10;i>0;i--)); do
-	if [ ! -e "/dev/mapper/$dm" ] ||
-	       cmd="dmsetup remove $dm"
-	       output=$(eval "$cmd" 2>&1); then
-	    echo "done"
-	    break
+	if [ ! -e "$1" ]; then
+	   break
 	fi
-	echo "$cmd: $output; retrying"
-	stop_bdev_users "$(readlink -f "/dev/mapper/$dm")"
-	sleep .1
+	cmd="dm=\$(dev_to_mpath \"$1\")"
+	if ! eval "$cmd"; then
+	    echo "$cmd: failed"
+	else
+	    t1=$(dmsetup table "$dm")
+	    cmd="dmsetup message $dm 0 fail_if_no_path"
+	    if ! eval "$cmd"; then
+		echo "$cmd: failed"
+	    else
+		t2=$(dmsetup table "$dm")
+		if echo "$t2" | grep -qw queue_if_no_path; then
+		    echo "$dm: $t1 -> $t2"
+		fi
+		cmd="dmsetup remove $dm"
+		if ! output=$(eval "$cmd" 2>&1); then
+		    echo "$cmd: $output; retrying"
+		else
+		    echo "done"
+		    break
+		fi
+	    fi
+	fi
+	if [ ! -e "$1" ]; then
+	   break
+	fi
+	ls -l "$1"
+	stop_bdev_users "$(readlink -f "$1")"
+	sleep .5
     done
     if [ $i = 0 ]; then
 	echo "failed"
